name: emobies_app
description: Emobies mobile repair app
version: 1.0.4+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:          # ← FIXED
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0    # ← FIXED
