name: emobies_app
description: Emobies — Mobile Repair · TheWall · Emowall AI
publish_to: 'none'
version: 1.0.6+106

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  web_socket_channel: ^2.4.0
  flutter_secure_storage: ^9.2.2
  go_router: ^13.2.0
  provider: ^6.1.2
  local_auth: ^2.3.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  fl_chart: ^0.68.0
  intl: ^0.19.0
  url_launcher: ^6.3.0
  share_plus: ^9.0.0
  package_info_plus: ^8.0.0
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
